-- Drop existing tables if they exist (clean setup)
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS top_character_stats CASCADE;
DROP TABLE IF EXISTS official_sections CASCADE;
DROP TABLE IF EXISTS official_metrics CASCADE;
DROP TABLE IF EXISTS source_snapshots CASCADE;
DROP TABLE IF EXISTS participants CASCADE;
DROP TABLE IF EXISTS killer_info CASCADE;
DROP TABLE IF EXISTS loadouts CASCADE;
DROP TABLE IF EXISTS matches CASCADE;

-- Create matches table
CREATE TABLE matches (
    id TEXT PRIMARY KEY,
    source_id TEXT,
    played_at TEXT NOT NULL,
    role TEXT NOT NULL,
    character TEXT,
    map TEXT,
    map_realm TEXT,
    duration_sec INTEGER,
    result TEXT,
    score INTEGER,
    raw_json JSONB,
    imported_at TEXT NOT NULL,
    user_email TEXT
);

CREATE INDEX idx_matches_date ON matches(played_at);
CREATE INDEX idx_matches_role ON matches(role);
CREATE INDEX idx_matches_user_email ON matches(user_email);

-- Create loadouts table
CREATE TABLE loadouts (
    match_id TEXT PRIMARY KEY REFERENCES matches(id) ON DELETE CASCADE,
    perks_json JSONB,
    item TEXT,
    addons_json JSONB,
    offering TEXT
);

-- Create killer_info table
CREATE TABLE killer_info (
    match_id TEXT PRIMARY KEY REFERENCES matches(id) ON DELETE CASCADE,
    killer TEXT,
    kills_count INTEGER,
    perks_json JSONB,
    addons_json JSONB,
    offering TEXT
);

-- Create participants table
CREATE TABLE participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id TEXT REFERENCES matches(id) ON DELETE CASCADE,
    character TEXT,
    role TEXT,
    result TEXT,
    score INTEGER,
    perks_json JSONB,
    item TEXT,
    addons_json JSONB,
    offering TEXT
);

-- Create source_snapshots table
CREATE TABLE source_snapshots (
    id TEXT PRIMARY KEY,
    source_url TEXT,
    kind TEXT,
    captured_at TEXT,
    raw_json JSONB,
    user_email TEXT
);

CREATE INDEX idx_snapshots_user_email ON source_snapshots(user_email);

-- Create official_metrics table
CREATE TABLE official_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_at TEXT NOT NULL,
    label TEXT NOT NULL,
    value TEXT NOT NULL,
    source_url TEXT NOT NULL,
    user_email TEXT
);

CREATE INDEX idx_metrics_user_email ON official_metrics(user_email);

-- Create official_sections table
CREATE TABLE official_sections (
    section TEXT NOT NULL,
    period TEXT NOT NULL,
    role TEXT NOT NULL,
    captured_at TEXT NOT NULL,
    raw_json JSONB NOT NULL,
    user_email TEXT NOT NULL DEFAULT 'default',
    PRIMARY KEY (section, period, role, user_email)
);

-- Create top_character_stats table
CREATE TABLE top_character_stats (
    section TEXT NOT NULL,
    period TEXT NOT NULL,
    role TEXT NOT NULL,
    character TEXT NOT NULL,
    captured_at TEXT NOT NULL,
    raw_json JSONB NOT NULL,
    user_email TEXT NOT NULL DEFAULT 'default',
    PRIMARY KEY (section, period, role, user_email)
);

-- Create assets table
CREATE TABLE assets (
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    PRIMARY KEY (type, name)
);
